# Generated by Django 5.2.8 on 2025-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.IntegerField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('authors', models.CharField(db_index=True, max_length=500)),
                ('average_rating', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('isbn13', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('num_pages', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ratings_count', models.IntegerField(db_index=True, default=0)),
                ('text_reviews_count', models.IntegerField(db_index=True, default=0)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('publisher', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-average_rating', 'title'],
                'indexes': [models.Index(fields=['title', 'authors'], name='books_book_title_313090_idx'), models.Index(fields=['average_rating', 'ratings_count'], name='books_book_average_cc2c04_idx')],
            },
        ),
    ]
